apiVersion: v1
kind: Secret
metadata:
  name: freightflow-secrets
  namespace: freightflow
  labels:
    app.kubernetes.io/name: freightflow
type: Opaque
stringData:
  JWT_SECRET: "replace-with-32-plus-character-random-secret"
  JWT_REFRESH_SECRET: "replace-with-32-plus-character-random-refresh-secret"
  MONGODB_URI: "mongodb://freightflow:replace-me@mongodb:27017/freightflow?authSource=admin"
  MONGO_INITDB_ROOT_USERNAME: "freightflow"
  MONGO_INITDB_ROOT_PASSWORD: "replace-with-strong-mongodb-password"
